firstpc
tnmtvv/SLAMBackendAlgos pull request #1
Opened 2022-03-14 08:01 UTC by tnmtvv

2022-03-16 12:16 UTC, DmiitriyJarosh requested changes

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +extract_data_depth = cv2.imread('depth.png', cv2.IMREAD_ANYDEPTH)
Почитайте про конструкцию if __name__ == "__main__":
Стоит ее использовать

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +color_matrix = np.array(extract_data_colors)
разве cv сразу не читает в numpy массив?

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +rows, colums, three = color_matrix.shape
three - это называется channels

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +color_matrix_right_shape = color_matrix.reshape(rows* colums, 3)
тут можно назвать переменную с использованием слова flattened - так как вы две размерности в одну превратили

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +color_matrix_right_shape = color_matrix.reshape(rows* colums, 3)
rows* - пробел пропущен

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +    matrix_u[i,j] = i
такие циклы полностью убивают весь эффект матриц - медленно будет работать( Numpy умеет делать почти все своими операторами, в данном случае гляньте на https://numpy.org/doc/stable/reference/generated/numpy.tile.html

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +      matrix_cx[i,j] = cx
можно вообще не создавать эту матрицу, numpy умеет сам понимать что в ситуации "матрица - число" нужно число поэлементно отнимать

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +  x_over_z = (matrix_cx - u) * 1/focal_x
вот cx - u сработало бы также как то что сейчас

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +      z_matrix[i,j] = depth[i,j]/ 5000
копировать тоже можно матрично - просто уберите циклы и индексы, numpy все сделает сам ->  `z_matrix = depth /  5000 `

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +      z_matrix[i,j] = depth[i,j]/ 5000
тогда и создавать z матрицу не придется заранее

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +    matrix_xyz[i,j] = (x[i,j], y[i,j], z[i,j])
матрицы можно объединить в одну с помощью оператора в numpy - посмотрите какие есть (vstack, dstack и тд)

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +answ_matrix = matrix_xyz.reshape(rows*colums, 3)
rows*colums - а где пробелы вокруг умножения?)

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +points = np.asarray(pc.points)
что это, вы же сами только что туда свой массив отдали.... Он не меняется

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +pc.colors = o3d.utility.Vector3dVector(color_matrix_right_shape)
а цвет разве нормализован сейчас? в opencv читается в диапазне [0, 255], а не нормалихованный

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +colors = None
все что дальше - это лишнее (да, в colab конечно так можно визуализировать, а в обычном скрипте лучше использовать open3d.visualization - там есть метод который умеет сам все рисовать просто по облаку)

2022-03-16 12:16 UTC, DmiitriyJarosh commented on pointCloud.py
> +colors = None
но за то что смогли визуализировать в колабе, где open3d.visualization не работает - большая умница!

2022-03-31 17:12 UTC, DmiitriyJarosh requested changes

2022-03-31 17:12 UTC, DmiitriyJarosh commented on equations.py
> +      k += 1
что это, это же for k само увеличивается, что за магия?

2022-03-31 17:12 UTC, DmiitriyJarosh commented on equations.py
> +    k = 0
и объявлять не надо заранее

2022-03-31 17:12 UTC, DmiitriyJarosh commented on equations.py
> +    for k in range(num_of_points):
нэйминг k

2022-03-31 17:12 UTC, DmiitriyJarosh commented on equations.py
> +  if (color !=[0,0,0]).all():        #for every unique color
можно предварительно фильтрануть filter() используя и тут написать уже enumerate(colors_unique) - тогда i не придется считать самой

2022-03-31 17:26 UTC, tnmtvv commented on pointCloud.py
> +color_matrix = np.array(extract_data_colors)
там фигня какая-то читается, цвета не различить, только если вот так переводить (9

2022-04-02 07:39 UTC, DmiitriyJarosh commented
.idea в gitignore - ее не надо заливать

2022-04-02 08:10 UTC, DmiitriyJarosh requested changes

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +    rows, columns, channels = color_matrix.shape
а зачем нам channels? можно заменить на _ - так обозначают не использ переменную

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +    columns_indices = np.arange(0, columns)
старт с 0 по дефолту же

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +    x, y, z, = convert_from_plane_to_3d(matrix_u, matrix_v, matrix_depth, cx=319.50, cy=239.50, focal_x=481.20,
такие длинные строки лучше по кодстайлу делать - функция и открытие скобки, потом с новой строки каждый аргумент и еще строка с закр скобкой

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +    reshaped_color_matrix = color_matrix.reshape(-1, color_matrix.shape[2])  # reshape matrix in order to get unique colors
чем этот решэйп отличается от прошлого? почему они по разному записаны?

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +    num_colors, channels = colors_unique.shape
опять же - зачем channels, можно просто было colors_unique.shape[0] присвоить

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +    num_colors, channels = colors_unique.shape
нэйминг - не понятно что это кол-во уникальных

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +    num_of_points, xyz = reshaped_color_matrix.shape
xyz - лишнее

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +        if (color != [0, 0, 0]).all():  # for every unique color
фильтруйте на черный  отдельно - лучше сделать маленький иф который выполняет continue при обнаружении цвета, чем пихать много кода в if с отрицанием - минимизируем отступы таким образом

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +            for k in range(num_of_points):
здесь нужно получить все индексы через np.where а не циклом

2022-04-02 08:10 UTC, DmiitriyJarosh commented on equations_/main.py
> +            equations[i] = np.array(get_normal(plane_points_array))  # getting equation out of plane
equations лучше сделать списком - чтобы не использовать i дополнительно, а в конце просто перевести в np.array

2022-04-03 06:26 UTC, DmiitriyJarosh requested changes

2022-04-03 06:26 UTC, DmiitriyJarosh commented on equations.py
> +    rows, columns, channels = color_matrix.shape
а channels где используется?

2022-04-03 06:26 UTC, DmiitriyJarosh commented on equations.py
> +    unique_colors_without_black = filter(lambda x: x != [0, 0, 0], colors)
Эта штука срабатывает без всяких .all()?

2022-04-03 06:26 UTC, DmiitriyJarosh commented on equations.py
> +            plane_points.append(matrix_of_points[index])
Питон умеет умно индексировать -> matrix_of_points[indices[0]] даст тоже самое что сбор в цикле этого списка

2022-04-03 06:26 UTC, DmiitriyJarosh commented on equations.py
> +        equations.append(np.array(get_normal(plane_points_array)))  # getting equation out of plane
давайте np.array перенесем внутрь get_normal - ее значения думаю всегда будут использоваться в таком виде

2022-04-04 06:27 UTC, tnmtvv commented on equations.py
> +        equations.append(np.array(get_normal(plane_points_array)))  # getting equation out of plane
не оч поняла, у меня же get normal 4 аргумента возвращает, их надо наверное в массив обернуть, чтобы к equations добавить или питон это тоже сам сделает?)0

2022-04-04 09:00 UTC, DmiitriyJarosh commented on equations.py
> +    n = eigvects[:,min_index]
Пробельчик пропущен - [:,min_index]

2022-04-05 12:36 UTC, DmiitriyJarosh approved these changes

2022-04-05 16:14 UTC, merged