Trajectory
tnmtvv/SLAMBackendAlgos pull request #2
Opened 2022-04-10 19:12 UTC by tnmtvv

2022-04-14 06:53 UTC, DmiitriyJarosh requested changes

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +    for i in range(len(array)):
у питона есть метод join у строк, он позволяет склеить элементы массива в строку, используя опр разделитель

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +def color_to_string(array):
а еще в питоне можно указывать типы, чтобы было проще потом код читать + статич анализ pycharm мог работать лучше - можно почитать про пакет typing

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +    answ = np.asarray([n[0], n[1], n[2], -np.dot(n, c)])
можно заинлайнить в ретурн

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +            array_of_colors.update({color_string: indx})
мапы умеют работать с индексацией - `array_of_colors[color_string] = indx`

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +            if array_of_colors.get(color_string, 'none') == 'none':  # if the plane is new
`if color_string in array_of_colors`

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +            if array_of_colors.get(color_string, 'none') == 'none':  # if the plane is new
почему вообще мапа называется array_of_colors? мб color_to_indx?

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +            if array_of_colors.get(color_string, 'none') == 'none':  # if the plane is new
почему нельзя выкинуть верхнюю ветку и всегда использовать только этот кусок? что так что так кладем только новые цвета

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +        plane_points_array = np.array(plane_points)
а до этого это был не np.array?

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +        plane_points = points[indices[0]]
если вы знаете что полезными будут только indices[0] - то лучше прямо при вызове np.where их выделить, чтобы дальше не индексировать уже везде

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +    x, y, z, = convert_from_plane_to_3d(
сейчас фиксированы параметры камеры, но если захотим запускать на др датасете, то будет неприятно, лучiе вынести их в параметры, а чтобы не было 6 параметров - сделать отдельный об]ект camera intrinsics

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +    matrix_xyz = np.dstack((x, y, z))
лучше перенести внутрь функции что производит эти x, y, z

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +        n1 = graph.add_node_pose_3d(geometry.SE3())
n1 - не понятно что это значит, надо переименовать

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +        equations[n] = list(map(lambda x: (x[0] * np.sign(x[0][-1]), x[1]), equations[n]))
я бы перенес эту логику в место где считается нормаль - чтобы все ее модификации были рядом и не надо было искать

2022-04-14 06:53 UTC, DmiitriyJarosh commented on Trajectory.py
> +    gt_rotation = np.asarray([[2 * (q[0] * q[0] + q[1] * q[1]) - 1, 2 * (q[1] * q[2] + q[0] * q[3]), 2 * (q[1] * q[3] - q[0] * q[2])],
в отдельную функцию + ссылка на формулу

2022-04-14 06:53 UTC, DmiitriyJarosh commented on equations.py
>  def get_normal(points):
правильно понимаю, что сейчас у нас код дублируется в двух файлах? давайте разделим, пусть будет файл plane_extraction, который умеет картинки читать, нормали искать и файл main в котором будет наш мэйн и плюс работа с mrob

2022-04-15 12:00 UTC, tnmtvv commented on Trajectory.py
> +    for i in range(len(array)):
вроде он только если элементы массива - строки работает

2022-04-17 05:08 UTC, tnmtvv commented on equations.py
>  def get_normal(points):
а один к другому как header подключить или как?

2022-04-19 17:19 UTC, DmiitriyJarosh requested changes

2022-04-19 17:19 UTC, DmiitriyJarosh commented on Trajectory.py
> +
зачем здесь пустая строка, кажется что по смыслу эти три строки вместе

2022-04-19 17:19 UTC, DmiitriyJarosh commented on Trajectory.py
> +    matrix_depth = cv2.imread(path_depth, cv2.IMREAD_ANYDEPTH)
матрицы давайте однообразно назовем, а то где то слово матрица сначала, где то color))

2022-04-19 17:19 UTC, DmiitriyJarosh commented on Trajectory.py
> +    import numpy as np
кажется тут случайно кусок файла вставился?

2022-04-20 07:07 UTC, DmiitriyJarosh requested changes

2022-04-20 07:07 UTC, DmiitriyJarosh commented on plane_extraction.py
> +    normal = (int)(np.sign(d)) * n
разве в питоне приведение не через int(x)?

2022-04-20 07:07 UTC, DmiitriyJarosh commented on plane_extraction.py
> +        indices = np.where((point_colors == color).all(axis=1))
может обьединить с прошлым фором?

2022-04-20 07:07 UTC, DmiitriyJarosh commented on Trajectory.py
> +if __name__ == '__main__':
имена файлов пишем с маленькой буквы, если только это не файл класса. Но тут вроде бы класса нет

2022-04-27 11:11 UTC, DmiitriyJarosh requested changes

2022-04-27 11:11 UTC, DmiitriyJarosh commented on Trajectory.py
> +    for i, _ in enumerate(depths):
а почему прочерк, если мы используем потом индексацию?

2022-04-27 11:11 UTC, DmiitriyJarosh commented on Trajectory.py
> +    viceversa = {} # and one more map (max_num_points: indx)
давайте имя попонятнее придумаем

2022-04-27 11:11 UTC, DmiitriyJarosh commented on Trajectory.py
> +    ten_max_points = sorted(list_of_max_points)[-10:]
points? мб planes?

2022-04-27 11:11 UTC, DmiitriyJarosh commented on Trajectory.py
> +        equations_of_image = plane_extraction.equation_extraction(points_of_image, colors_of_image, planes_matcher, ten_max_indices)
`plane_extraction` - от этого нужно избавиться

2022-04-27 11:11 UTC, DmiitriyJarosh commented on Trajectory.py
> +    for i in range(num_of_nodes):
все еще очень много в мэйне, визуализацию можно точно отделить

2022-04-27 11:11 UTC, DmiitriyJarosh commented on Trajectory.py
> +    for i, pc in enumerate(reversed(point_clouds)):
давайте сделаем красиво и `zip(point_clouds, graph_estimaed_state )`, только сделайте аккуратно чтобы сопоставляло верно

2022-04-27 11:11 UTC, DmiitriyJarosh commented on plane_extraction.py
> +def building_maps(points, point_colors):
название функции непонятное

2022-04-27 11:11 UTC, DmiitriyJarosh commented on plane_extraction.py
> +    map_indx_max_num_points = {}  # map (indx: max_num_points)
а что это за комменты? Используйте typing встроенный в питон

2022-04-27 11:11 UTC, DmiitriyJarosh commented on plane_extraction.py
> +    unique_colors_without_black = filter(lambda x: (x != [0, 0, 0]).all(axis=0), colors_unique)
а комменты выше нужны?

2022-05-02 06:55 UTC, DmiitriyJarosh requested changes

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +from typing import List
имя файла  trajectory.py с маленькой буквы - этот коммент я уже писал!

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    in_file = open(path).read().splitlines()  # getting gt data
а file.readlines() не будет заменой `read().splitlines()`?

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    gt_matrix_01 = gt_matrices[0]
почему это resolved а ничего не исправлено?

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    last_gt_matrix = gt_matrices[num_of_nodes - 1]  # measuring error only by the last matrix
почему не просто` [-1]`?

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    gt_matrix_01 = gt_matrices[0]
а где вообще это используется?

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    for i in range(num_of_nodes):
эта часть не зависит от плоскостей, ее можно вынести туда где создается граф

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +            if plane.index not in set_indx:
а это двойная работа - давайте добавлять плоскости в граф в `estimate_the_graph()` - там у нас есть мапа с их уникальными индексами - и не нужен будет дополнительный сет, можно просто добавить столько плоскостей сколько элементов в мапе

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +def visualisation(graph_estimaed_state, num_of_nodes, matrices_of_points, colors):
`graph_estimaed_state` -> `graph_estimated_state`

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    ten_max_points = sorted(list_of_max_points)[-10:]
ау

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    for key, value in map_indx_points.items():
это лишнее, можно взять `map_indx_points.values()` - там будут пары key, value и отсортировать их по второму элементу (используя лямбду при сортировке)

2022-05-02 06:55 UTC, DmiitriyJarosh commented on Trajectory.py
> +    num_of_nodes = len(depths)
`dataset_nodes` ведь передается из аргументов))

2022-05-11 12:50 UTC, tnmtvv commented on Trajectory.py
> +    for i in range(num_of_nodes):
если менять местами циклы добавления, ломается, видимо важен порядок, как строить граф, я чуть по-другому исправлю

2022-05-11 16:49 UTC, DmiitriyJarosh requested changes

2022-05-11 16:49 UTC, DmiitriyJarosh commented on plane_extraction.py
> +def building_maps(points, point_colors, color_to_index, indx_to_max_num_points):
build_color_index кажется звучит получше

2022-05-11 16:49 UTC, DmiitriyJarosh commented on plane_extraction.py
> +        indices = np.where((point_colors == color).all(axis=1))
давайте сразу брать нулевой элемент, разве другой где то используется?

2022-05-11 16:49 UTC, DmiitriyJarosh commented on plane_extraction.py
> +        if (cur_indx in indx_to_max_num_points and len(indices[0]) > indx_to_max_num_points[cur_indx]) \
ien(indices) - в переменную, чтоб два раза не считать

2022-05-11 16:49 UTC, DmiitriyJarosh commented on plane_extraction.py
> +        indices = np.where((point_colors == color).all(axis=1))
аналогично сразу [0]

2022-05-11 16:49 UTC, DmiitriyJarosh commented on plane_extraction.py
> +            plane = Plane(get_normal(plane_points), color_to_index[color_string])
у нас есть cur_indx уже

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    gt_matrices = read_gt_poses('gt.txt', dataset_nodes)
не хардкодим в код имена файлов

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    gt_matrices = read_gt_poses('gt.txt', dataset_nodes)
`dataset_nodes` - это что? если количетсво, то надо чтобы в названии было это понятно (nodes_count)

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    last_gt_matrix = gt_matrices[num_of_nodes - 1]  # measuring error only by the last matrix
мы же возвращаем нужное число, можно `-1` использовать

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    gt_matrix_01 = gt_matrices[0]
это все еще неверно названо)

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    matrix_gt_the_last = np.append(last_gt_matrix, [[0, 0, 0, 1]], axis=0)
matrix_gt_se3

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    matrix_gt_first = np.append(gt_matrix_01, [[0, 0, 0, 1]], axis=0)
same

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    the_last_estimated_node = geometry.SE3(graph_estimated_state[-1])
the - лишнее

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    absolute_to_the_last_gt = np.linalg.inv(matrix_gt_first) @ matrix_gt_the_last
the - пропускаем

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    for i in range(num_of_nodes):
эта цифра известна заранее, можно при билде графа проставить позы) Кажется этот коммент уже был

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +            if plane.index not in set_indx:
давайте переписывать на меньшую вложенность - `if plane.index in set_indx: continue` так код получается менее ступенчатым

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    map_cloud_matrix = {point_clouds: graph_estimaed_state for point_clouds, graph_estimaed_state in zip(reversed(point_clouds), reversed(graph_estimaed_state))}
`cloud_to_estimated_state`

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    map_indx_points = {}
называем маппы правильно!

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    planes_matcher = {}
plane to index

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    max_points_indx = {}
тоже самое про нэйминг

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    list_of_max_points = list(map_indx_points.values())
зачем выносить в переменную, нам нужны только 10

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +        ten_max_indices.append(max_points_indx[points])
генератор

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +    plane_index_to_real_index = {}
зачем создавать здесь? почему не в функции

2022-05-11 16:49 UTC, DmiitriyJarosh commented on trajectory.py
> +if __name__ == '__main__':
выносим в файл main.py

2022-06-05 10:16 UTC, DmiitriyJarosh approved these changes

2022-06-05 10:16 UTC, merged